platform :ios, '8.0'

xcodeproj 'SwiftMeiTuanDemoApp.xcodeproj'

target 'SwiftMeiTuanDemoApp' do
pod 'Masonry'
pod 'ReactiveCocoa', '~> 7.0'
pod 'MJRefresh'
pod 'SDWebImage/WebP'
pod 'AFNetworking', '~> 3.0'

end


